CREATE TABLE IF NOT EXISTS articles (
    DOI VARCHAR(50), 
    URL TEXT, 
    TITLE TEXT, 
    YEAR INT, 
    OUTLET TEXT,
    VOLUME INT,
    NUMBER INT,
    AUTHOR_NAME TEXT,
    INSTITUTION TEXT, 
    INSTITUTION_DEPARTMENT TEXT, 
    INSTITUTION_CITY TEXT, 
    INSTITUTION_COUNTRY TEXT);
