INSERT INTO articles (
    DOI,
    URL,
    TITLE,
    YEAR,
    OUTLET,
    VOLUME,
    NUMBER,
    AUTHOR_NAME,
    INSTITUTION,
    INSTITUTION_DEPARTMENT,
    INSTITUTION_CITY,
    INSTITUTION_COUNTRY) VALUES (?)